version: "3"
services:
  grafana:
    build: ./grafana
    #image: k0rventen/apple-health-grafana-grafana
    ports:
    - 3000:3000
    volumes:
    - grafana-data:/var/lib/grafana
  influx:
    image: influxdb:1.8
    environment:
      - INFLUXDB_DB=health
    volumes:
    - influx-data:/var/lib/influxdb
  ingester:
    #image: k0rventen/apple-health-grafana-ingester
    build: ./ingester
    volumes:
    - ./export-shortcuts.zip:/export.zip

volumes:
  influx-data:
  grafana-data:
