{
 "title": "Apple health specific metrics",
 "time": { "from": "now-2y", "to": "now" },
 "panels": [
  { "title": "Daily Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Distance walked per day",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "DistanceWalkingRunning",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Minutes of exercise per day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "AppleExerciseTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Steps per day",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "steps" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "StepCount",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Energy burned per day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "alias": "Active Energy burned",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ActiveEnergyBurned",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " * 1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Basal Energy burned",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "BasalEnergyBurned",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " * 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Time spend standing up",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "AppleStandTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Heart infos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Heart infos (per day)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "targets": [
    {
     "alias": "Walking heart rate",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "WalkingHeartRateAverage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "Resting heart rate",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "RestingHeartRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Min/Max heart rate (per day)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "targets": [
    {
     "alias": "Lowest heart rate",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "HeartRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    },
    {
     "alias": "Lowest heart rate",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "HeartRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heart rate variability",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "HeartRateVariabilitySDNN",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of low and high heart rate events per day ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "targets": [
    {
     "alias": "Low heart rate events",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "LowHeartRateEvent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "High heart rate events",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "HighHeartRateEvent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heart rate through the day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Active time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AppleExerciseTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Heart rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "unit" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HeartRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}